package com.estoq;

import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Valida as migrações V1-V3 num PostgreSQL real embutido (Zonky), simulando o
 * banco legado de produção: tabelas sem restaurante_id, uniques globais antigos
 * e o admin ativo — exatamente o cenário do deploy de 2026-09-24.
 */
class MigracaoProdValidacaoTest {

    static EmbeddedPostgres pg;
    static String jdbcUrl;

    @BeforeAll
    static void subir() throws Exception {
        pg = EmbeddedPostgres.builder().start();
        jdbcUrl = pg.getJdbcUrl("postgres", "postgres");
        try (Connection conn = DriverManager.getConnection(jdbcUrl);
             Statement st = conn.createStatement()) {
            // Usuários legado + admin ativo (o que existia antes do multi-tenant).
            st.execute("create table usuarios (id bigint generated by default as identity primary key, " +
                    "nome varchar(120) not null, email varchar(254) not null unique, senha varchar(120) not null, " +
                    "perfil varchar(30) not null, ativo boolean not null default true, " +
                    "data_hora_criacao timestamp(6) not null, version bigint not null default 0)");
            st.execute("insert into usuarios (nome, email, senha, perfil, ativo, data_hora_criacao) " +
                    "values ('Admin EstoQ', 'admin@estoq.com', 'x', 'ADMIN', true, now())");
            // 15 tabelas de negócio legadas (apenas o essencial; as migrações só ADD/DROP).
            String[] tabelas = {"ajustes", "alertas", "auditoria", "balancos", "categorias",
                    "configuracoes_balanco", "consumos", "desperdicios", "entradas", "itens_balanco",
                    "movimentacoes", "parametros_cmv", "produtos", "produtos_abertos"};
            for (String t : tabelas) {
                st.execute("create table " + t + " (id bigint generated by default as identity primary key)");
            }
            // lotes e parametros_estoque com os uniques globais antigos + dados.
            st.execute("create table lotes (id bigint generated by default as identity primary key, codigo varchar(60) not null)");
            st.execute("alter table lotes add constraint uk_lotes_codigo unique (codigo)");
            st.execute("insert into lotes (codigo) values ('L-0001')");
            st.execute("create table parametros_estoque (id bigint generated by default as identity primary key, produto_id bigint)");
            st.execute("alter table parametros_estoque add constraint uk_parametros_estoque_produto unique (produto_id)");
        }
    }

    @AfterAll
    static void derrubar() throws Exception {
        if (pg != null) {
            pg.close();
        }
    }

    @Test
    void migracoesAplicamNumBancoLegado() throws Exception {
        Flyway flyway = Flyway.configure()
                .dataSource(jdbcUrl, "postgres", "postgres")
                .baselineOnMigrate(true)
                .baselineVersion("0")
                .locations("classpath:db/migration")
                .load();
        var resultado = flyway.migrate();
        assertEquals(3, resultado.migrationsExecuted, "V1+V2+V3 devem executar");

        try (Connection conn = DriverManager.getConnection(jdbcUrl);
             Statement st = conn.createStatement()) {

            // "EstoQ Padrão" criado e dono dos dados herdados.
            try (ResultSet rs = st.executeQuery("select count(*) from restaurantes where nome = 'EstoQ Padrão'")) {
                rs.next();
                assertEquals(1, rs.getInt(1));
            }

            // Admin promovido a PLATAFORMA, restaurante_id null.
            try (ResultSet rs = st.executeQuery("select perfil, restaurante_id from usuarios where email = 'admin@estoq.com'")) {
                rs.next();
                assertEquals("PLATAFORMA", rs.getString(1));
                assertNull(rs.getObject(2));
            }

            // Dados herdados backfillados para o restaurante 1.
            try (ResultSet rs = st.executeQuery("select restaurante_id from lotes")) {
                rs.next();
                assertEquals(1L, rs.getLong(1));
            }

            // Uniques antigos fora; novos (tenant) presentes.
            try (ResultSet rs = st.executeQuery("select conname from pg_constraint " +
                    "where conrelid = 'lotes'::regclass and contype = 'u' order by conname")) {
                assertEquals(List.of("uk_lotes_tenant_codigo"), coletar(rs));
            }

            // As 17 tabelas ganharam FK -> restaurantes.
            try (ResultSet rs = st.executeQuery("select count(*) from pg_constraint " +
                    "where contype = 'f' and confrelid = 'restaurantes'::regclass")) {
                rs.next();
                assertEquals(17, rs.getInt(1));
            }

            // Identidade funcional (INSERT sem id no PG real).
            try (ResultSet rs = st.executeQuery("insert into restaurantes (nome, ativo, data_hora_criacao, version) " +
                    "values ('Loja Nova', true, now(), 0) returning id")) {
                rs.next();
                assertTrue(rs.getLong(1) > 1);
            }
        }
    }

    private List<String> coletar(ResultSet rs) throws Exception {
        List<String> nomes = new ArrayList<>();
        while (rs.next()) {
            nomes.add(rs.getString(1));
        }
        return nomes;
    }
}