package com.estoq;

import io.zonky.test.db.postgres.embedded.EmbeddedPostgres;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Valida as migrações V1-V3 num PostgreSQL real embutido (Zonky) em dois cenários:
 * 1) banco legado "limpo" (sem nenhuma coluna de tenant);
 * 2) estado real de produção de 2026-09-24 (ddl-auto=update já criou restaurante_id
 *    em 9 das 17 tabelas e também a tabela restaurantes — que o deploy "drop+recreate"
 *    já resolveu via V1 aplicada; aqui simulamos as 9 tabelas armadas).
 */
class MigracaoProdValidacaoTest {

    static EmbeddedPostgres pg;
    static String jdbcUrl;

    static final String[] TABELAS = {"ajustes", "alertas", "auditoria", "balancos", "categorias",
            "configuracoes_balanco", "consumos", "desperdicios", "entradas", "itens_balanco",
            "lotes", "movimentacoes", "parametros_cmv", "parametros_estoque", "produtos",
            "produtos_abertos", "usuarios"};

    /** As 9 tabelas em que a produção 2026-09-24 tinha a coluna via ddl-auto=update. */
    static final List<String> ARMADAS_COM_COLUNA = List.of(
            "alertas", "auditoria", "balancos", "itens_balanco", "lotes",
            "movimentacoes", "parametros_estoque", "produtos", "produtos_abertos");

    @BeforeAll
    static void subir() throws Exception {
        pg = EmbeddedPostgres.builder().start();
        jdbcUrl = pg.getJdbcUrl("postgres", "postgres");
    }

    @AfterAll
    static void derrubar() throws Exception {
        if (pg != null) {
            pg.close();
        }
    }

    @Test
    void migracoesAplicamNumBancoLegado() throws Exception {
        criarLegado(null, List.of());
        rodarMigracoes(null);
        validarResultado(null);
    }

    @Test
    void migracoesAplicamNoEstadoParcialDeProducao() throws Exception {
        criarLegado("s2", ARMADAS_COM_COLUNA);
        rodarMigracoes("s2");
        validarResultado("s2");
    }

    private void criarLegado(String schema, List<String> tabelasArmadas) throws Exception {
        try (Connection conn = DriverManager.getConnection(jdbcUrl);
             Statement st = conn.createStatement()) {
            if (schema != null) {
                st.execute("create schema if not exists " + schema);
            }
            String prefixo = schema != null ? schema + "." : "";
            // Usuários legado + admin ativo.
            st.execute("create table " + prefixo + "usuarios (id bigint generated by default as identity primary key, "
                    + "nome varchar(120) not null, email varchar(254) not null unique, senha varchar(120) not null, "
                    + "perfil varchar(30) not null, ativo boolean not null default true, "
                    + "data_hora_criacao timestamp(6) not null, version bigint not null default 0)");
            st.execute("insert into " + prefixo + "usuarios (nome, email, senha, perfil, ativo, data_hora_criacao) "
                    + "values ('Admin EstoQ', 'admin@estoq.com', 'x', 'ADMIN', true, now())");
            // CHECK antigo do perfil (ddl-auto de versões anteriores não conhecia PLATAFORMA).
            st.execute("alter table " + prefixo + "usuarios add constraint usuarios_perfil_check "
                    + "check (perfil in ('ESTAGIARIO', 'ATENDENTE', 'COZINHEIRO', 'ADMIN'))");
            for (String t : TABELAS) {
                if ("usuarios".equals(t)) {
                    continue;
                }
                if ("lotes".equals(t)) {
                    st.execute("create table " + prefixo + "lotes (id bigint generated by default as identity primary key, codigo varchar(60) not null)");
                } else if ("parametros_estoque".equals(t)) {
                    st.execute("create table " + prefixo + "parametros_estoque (id bigint generated by default as identity primary key, produto_id bigint)");
                } else {
                    st.execute("create table " + prefixo + t + " (id bigint generated by default as identity primary key)");
                }
                if (tabelasArmadas.contains(t)) {
                    st.execute("alter table " + prefixo + t + " add column restaurante_id bigint");
                }
            }
            // Uniques globais antigos + dados de exemplo.
            st.execute("alter table " + prefixo + "lotes add constraint uk_lotes_codigo unique (codigo)");
            st.execute("insert into " + prefixo + "lotes (codigo) values ('L-0001')");
            st.execute("alter table " + prefixo + "parametros_estoque add constraint uk_parametros_estoque_produto unique (produto_id)");
        }
    }

    private void rodarMigracoes(String schema) {
        var configuracao = Flyway.configure()
                .dataSource(jdbcUrl, "postgres", "postgres")
                .baselineOnMigrate(true)
                .baselineVersion("0")
                .locations("classpath:db/migration");
        if (schema != null) {
            configuracao = configuracao.schemas(schema);
        }
        var resultado = configuracao.load().migrate();
        assertEquals(3, resultado.migrationsExecuted, "V1+V2+V3 devem executar");
    }

    private void validarResultado(String schema) throws Exception {
        String prefixo = schema != null ? schema + "." : "";
        String caminho = schema != null ? schema : "public";
        try (Connection conn = DriverManager.getConnection(jdbcUrl);
             Statement st = conn.createStatement()) {
            try (Statement s2 = conn.createStatement()) {
                s2.execute("select set_config('search_path', '" + caminho + "', false)");
            }
            try (ResultSet rs = st.executeQuery("select count(*) from restaurantes where nome = 'EstoQ Padrão'")) {
                rs.next();
                assertEquals(1, rs.getInt(1));
            }
            try (ResultSet rs = st.executeQuery("select perfil, restaurante_id from usuarios where email = 'admin@estoq.com'")) {
                rs.next();
                assertEquals("PLATAFORMA", rs.getString(1));
                assertNull(rs.getObject(2));
            }
            try (ResultSet rs = st.executeQuery("select restaurante_id from lotes")) {
                rs.next();
                assertEquals(1L, rs.getLong(1));
            }
            try (ResultSet rs = st.executeQuery("select conname from pg_constraint "
                    + "where conrelid = 'lotes'::regclass and contype = 'u' order by conname")) {
                assertEquals(List.of("uk_lotes_tenant_codigo"), coletar(rs));
            }
            try (ResultSet rs = st.executeQuery("select count(*) from pg_constraint "
                    + "where contype = 'f' and confrelid = 'restaurantes'::regclass")) {
                rs.next();
                assertEquals(17, rs.getInt(1));
            }
            try (ResultSet rs = st.executeQuery("insert into restaurantes (nome, ativo, data_hora_criacao, version) "
                    + "values ('Loja Nova', true, now(), 0) returning id")) {
                rs.next();
                assertTrue(rs.getLong(1) > 1);
            }
        }
    }

    private List<String> coletar(ResultSet rs) throws Exception {
        List<String> nomes = new ArrayList<>();
        while (rs.next()) {
            nomes.add(rs.getString(1));
        }
        return nomes;
    }
}