-- Schema completo na versão 4, aplicado pelo Flyway somente em bancos novos.
-- Bancos com histórico Flyway continuam usando V1-V4; não editar essas migrações.
-- Estrutura baseada nas entidades JPA, com FKs de tenant e usuário PLATAFORMA sem loja.

create table ajustes (
    restaurante_id bigint,
    id bigint not null,
    primary key (id)
);

create table alertas (
    ativo boolean not null,
    visualizado boolean not null,
    data_geracao timestamp(6) not null,
    data_hora_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    lote_id bigint,
    produto_id bigint,
    restaurante_id bigint not null,
    version bigint not null,
    perfil_destino varchar(20) not null check ((perfil_destino in ('ADMIN','COZINHA','NUTRICIONISTA','PLATAFORMA'))),
    tipo varchar(30) not null check ((tipo in ('ESTOQUE_BAIXO','PROXIMO_VENCIMENTO','VENCIDO','BALANCO_PENDENTE','DIFERENCA_ESTOQUE'))),
    mensagem varchar(300) not null,
    primary key (id)
);

create table auditoria (
    ativo boolean not null,
    data_hora timestamp(6),
    data_hora_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    restaurante_id bigint not null,
    version bigint not null,
    tipo varchar(40) not null,
    entidade varchar(60),
    entidade_id varchar(60),
    usuario_nome varchar(120),
    descricao varchar(400),
    primary key (id)
);

create table balanco_categorias (
    balanco_id bigint not null,
    categoria_id bigint not null
);

create table balancos (
    ativo boolean not null,
    data_hora timestamp(6) not null,
    data_hora_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    restaurante_id bigint not null,
    usuario_id bigint,
    version bigint not null,
    status varchar(20) not null check ((status in ('PENDENTE','EM_ANDAMENTO','CONCLUIDO'))),
    tipo varchar(20) not null check ((tipo in ('GERAL','PARCIAL'))),
    primary key (id)
);

create table categorias (
    ativo boolean not null,
    data_hora_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    restaurante_id bigint not null,
    version bigint not null,
    nome varchar(120) not null,
    descricao varchar(500),
    primary key (id)
);

create table cmv_receitas_periodo (
    ativo boolean not null,
    data_fim date not null,
    data_inicio date not null,
    receita_base numeric(18,2),
    data_hora_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    restaurante_id bigint not null,
    version bigint not null,
    primary key (id),
    constraint uk_cmv_receita_tenant_periodo unique (restaurante_id, data_inicio, data_fim)
);

create table configuracoes_balanco (
    ativo boolean not null,
    dia_execucao integer,
    proxima_execucao date,
    data_hora_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    restaurante_id bigint not null,
    version bigint not null,
    periodicidade varchar(20) not null check ((periodicidade in ('DIARIA','SEMANAL','MENSAL'))),
    primary key (id)
);

create table consumos (
    restaurante_id bigint,
    id bigint not null,
    primary key (id)
);

create table desperdicios (
    restaurante_id bigint,
    id bigint not null,
    motivo varchar(40) not null check ((motivo in ('VENCIMENTO','DETERIORACAO','PREPARO_INCORRETO','SOBRA_NAO_APROVEITADA','OUTRO'))),
    descricao_motivo varchar(500),
    primary key (id)
);

create table entradas (
    restaurante_id bigint,
    data_validade date,
    valor_total_pago numeric(18,2) not null,
    id bigint not null,
    unidade_compra varchar(255) not null check ((unidade_compra in ('KG','G','L','ML','UN'))),
    primary key (id)
);

create table itens_balanco (
    ajuste_aplicado boolean not null,
    ativo boolean not null,
    quantidade_fisica numeric(18,3),
    quantidade_sistema numeric(18,3) not null,
    balanco_id bigint not null,
    data_hora_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    produto_id bigint not null,
    restaurante_id bigint not null,
    version bigint not null,
    primary key (id)
);

create table lotes (
    ativo boolean not null,
    data_entrada date,
    data_validade date,
    preco_unitario numeric(18,6) not null,
    quantidade_atual numeric(18,3) not null,
    quantidade_inicial numeric(18,3) not null,
    data_hora_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    produto_id bigint not null,
    restaurante_id bigint not null,
    version bigint not null,
    codigo varchar(50) not null,
    primary key (id),
    constraint uk_lotes_tenant_codigo unique (restaurante_id, codigo)
);

create table movimentacoes (
    ativo boolean not null,
    quantidade numeric(18,3) not null,
    quantidade_anterior numeric(18,3) not null,
    quantidade_posterior numeric(18,3) not null,
    data_hora timestamp(6) not null,
    data_hora_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    item_balanco_id bigint,
    lote_id bigint,
    produto_aberto_id bigint,
    produto_id bigint not null,
    restaurante_id bigint not null,
    usuario_id bigint not null,
    version bigint not null,
    tipo varchar(20) not null check ((tipo in ('AJUSTE','CONSUMO','DESPERDICIO','ENTRADA'))),
    observacao varchar(500),
    primary key (id)
);

create table parametros_cmv (
    ativo boolean not null,
    percentual_ideal numeric(5,2) not null,
    data_atualizacao timestamp(6) not null,
    data_hora_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    restaurante_id bigint not null,
    version bigint not null,
    primary key (id)
);

create table parametros_estoque (
    ativo boolean not null,
    consumo_medio_diario numeric(18,3) not null,
    dias_alerta_vencimento integer not null,
    estoque_maximo numeric(18,3) not null,
    estoque_medio numeric(18,3) not null,
    estoque_minimo numeric(18,3) not null,
    periodo_analise_dias integer not null,
    tempo_reposicao_dias integer not null,
    data_atualizacao timestamp(6),
    data_hora_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    produto_id bigint not null unique,
    restaurante_id bigint not null,
    version bigint not null,
    primary key (id),
    constraint uk_parametros_estoque_tenant_produto unique (restaurante_id, produto_id)
);

create table produtos (
    ativo boolean not null,
    categoria_id bigint not null,
    data_hora_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    restaurante_id bigint not null,
    version bigint not null,
    unidade_medida varchar(20) not null check ((unidade_medida in ('KG','G','L','ML','UN'))),
    codigo_barras varchar(40),
    nome varchar(120) not null,
    primary key (id)
);

create table produtos_abertos (
    ativo boolean not null,
    finalizado boolean not null,
    quantidade_aberta numeric(18,3) not null,
    quantidade_utilizada numeric(18,3) not null,
    data_abertura timestamp(6) not null,
    data_hora_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    lote_id bigint not null,
    restaurante_id bigint not null,
    usuario_id bigint,
    version bigint not null,
    primary key (id)
);

create table restaurantes (
    ativo boolean not null,
    data_hora_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    version bigint not null,
    nome varchar(120) not null,
    primary key (id)
);

create table usuarios (
    ativo boolean not null,
    data_hora_criacao timestamp(6) not null,
    id bigint generated by default as identity,
    restaurante_id bigint,
    version bigint not null,
    perfil varchar(20) not null check ((perfil in ('ADMIN','COZINHA','NUTRICIONISTA','PLATAFORMA'))),
    senha varchar(100) not null,
    nome varchar(120) not null,
    email varchar(254) not null unique,
    primary key (id)
);

create index idx_alerta_aberto on alertas (tipo, visualizado, perfil_destino);

create index idx_balanco_status on balancos (status);

create index idx_balanco_data on balancos (data_hora);

create index idx_item_balanco_produto on itens_balanco (produto_id);

create index idx_item_balanco_balanco on itens_balanco (balanco_id);

create index idx_lote_produto on lotes (produto_id);

create index idx_lote_validade on lotes (data_validade);

create index idx_mov_tipo_data on movimentacoes (tipo, data_hora);

create index idx_mov_lote on movimentacoes (lote_id);

create index idx_mov_produto on movimentacoes (produto_id);

create index idx_produto_categoria on produtos (categoria_id);

create index idx_aberto_finalizado on produtos_abertos (finalizado);

create index idx_aberto_lote on produtos_abertos (lote_id);

alter table if exists ajustes add constraint FKkhom7x5lc4a6t7uffythnn8wi foreign key (id) references movimentacoes;

alter table if exists alertas add constraint FKkrwrd60bi27riyd9cv65udnsr foreign key (lote_id) references lotes;

alter table if exists alertas add constraint FKipqtgdhw6jqy0pdvjs1958b96 foreign key (produto_id) references produtos;

alter table if exists balanco_categorias add constraint FK9hkvsnc27djki0nnyk5egmd3j foreign key (categoria_id) references categorias;

alter table if exists balanco_categorias add constraint FK3st1dtxxx3bw7r3apf7m5d7l7 foreign key (balanco_id) references balancos;

alter table if exists balancos add constraint FK6rke0dsuar3tkunscpawfl232 foreign key (usuario_id) references usuarios;

alter table if exists consumos add constraint FKaw545vo3dh5mwshtg9y0toe09 foreign key (id) references movimentacoes;

alter table if exists desperdicios add constraint FKp5lllw5jlw7ar1ehysqtd1b87 foreign key (id) references movimentacoes;

alter table if exists entradas add constraint FKh5ih9kes01qrje4msgi238t7f foreign key (id) references movimentacoes;

alter table if exists itens_balanco add constraint FK40x5sm4qd6yh7k9gh6c1njo84 foreign key (balanco_id) references balancos;

alter table if exists itens_balanco add constraint FK5twohnpth5dfsv5gyg9a1uxd1 foreign key (produto_id) references produtos;

alter table if exists lotes add constraint FKqexy7wuxwrcg2dva37p4c1b7y foreign key (produto_id) references produtos;

alter table if exists movimentacoes add constraint FK69agc7i97ehx3x21jf0m56kfc foreign key (item_balanco_id) references itens_balanco;

alter table if exists movimentacoes add constraint FKhylylu2w46fdrw86yvecgbxw0 foreign key (lote_id) references lotes;

alter table if exists movimentacoes add constraint FK7nwbhaoq6lqh2wo48e2o5i25e foreign key (produto_id) references produtos;

alter table if exists movimentacoes add constraint FK3mdyi6fq0t48kltgpvhs0sjwf foreign key (produto_aberto_id) references produtos_abertos;

alter table if exists movimentacoes add constraint FKnx617rl2q4tiiqgu7uyalnl9b foreign key (usuario_id) references usuarios;

alter table if exists parametros_estoque add constraint FKrx541nlvcf4qxsgh661ol567s foreign key (produto_id) references produtos;

alter table if exists produtos add constraint FK8rqw0ljwdaom34jr2t46bjtrn foreign key (categoria_id) references categorias;

alter table if exists produtos_abertos add constraint FKjkrt9cxgunj2xryhgxalenyu6 foreign key (lote_id) references lotes;

alter table if exists produtos_abertos add constraint FKdmhx51sneymux20cfujk5s2kw foreign key (usuario_id) references usuarios;

alter table ajustes add constraint fk_ajustes_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table alertas add constraint fk_alertas_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table auditoria add constraint fk_auditoria_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table balancos add constraint fk_balancos_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table categorias add constraint fk_categorias_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table configuracoes_balanco add constraint fk_configuracoes_balanco_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table consumos add constraint fk_consumos_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table desperdicios add constraint fk_desperdicios_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table entradas add constraint fk_entradas_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table itens_balanco add constraint fk_itens_balanco_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table lotes add constraint fk_lotes_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table movimentacoes add constraint fk_movimentacoes_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table parametros_cmv add constraint fk_parametros_cmv_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table parametros_estoque add constraint fk_parametros_estoque_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table produtos add constraint fk_produtos_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table produtos_abertos add constraint fk_produtos_abertos_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table usuarios add constraint fk_usuarios_restaurante foreign key (restaurante_id) references restaurantes(id);
alter table cmv_receitas_periodo add constraint fk_cmv_receitas_periodo_restaurante foreign key (restaurante_id) references restaurantes(id);
