-- Restaurantes: o tenant que isola todos os dados de negócio.

create table restaurantes (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    ativo boolean not null default true,
    data_hora_criacao timestamp(6) not null,
    version bigint not null default 0
);