spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
server.servlet.session.cookie.secure=${SESSION_SECURE:false}
estoq.seed.enabled=${SEED_ENABLED:true}
estoq.cors.origins=${CORS_ORIGINS:http://localhost:5174,http://localhost:5173}
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
