spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
server.servlet.session.cookie.secure=${SESSION_SECURE:false}
estoq.seed.enabled=${SEED_ENABLED:true}
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
